// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itfflubtsrukdkwoydnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZmZsdWJ0c3J1a2Rrd295ZG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTY2ODMsImV4cCI6MjA3MTQzMjY4M30.om6GtdxP_JRscxw235gxK-j3AMXIEwBrQB2Y6Kj6p68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});